version: 0.2

phases:
  install:
    runtime-version:
      dotnet: 8.0
    commands:
      - echo "installing something"
  pre_build:
    commands:
      - chmod +x install-terraform.sh configure-named-profile.sh apply-terraform.sh # make files executable
      - ./install-terraform.sh
      - ./configure-named-profile.sh
  build:
    commands:
      - echo "we are in the build phase"
      - echo "we can run tests here"
      - grep -Fq "rumo" main.tf
  post_build:
    commands:
      - echo "we are in the post build phase"
# artifacts:
#   files:
#     - "**/*"
